### ISSUE TITLE
Can't build due to Editor only functions

### ISSUE THREAD

**Issue by foomanchu1234** [kkukshtel/castledb-unity-importer#1]
I had to place preprocessor directives (#if UNITY_EDITOR) around several parts to allow building my app.  I can send a PR if that helps. Thanks for writing this plugin, its freaking amazing and I will be contributing hopefully.

Thanks!

**Comment by foomanchu1234** [comment]
Thanks for the response!  It was a simple fix for me and I am now using your code to generate ScriptableObjects from the JSON since I still need the SOs.  Your plugin lets me design what my tiles will be and then I press a button and everything is done for me :).

**Comment by kkukshtel** [comment]
Oh woah! Did you rewrite the code generation stuff then? Didn't even think of this as a general JSON parser library! Also, going to see what I can do to make the repo build-compatible from the start.

**Comment by foomanchu1234** [comment]
I sent a PR with a potential fix for the build issue.
