### ISSUE TITLE
Floats are imported as integers 

### ISSUE THREAD

**Issue by ntilborg** [kkukshtel/castledb-unity-importer#15]
The SimpleJSON.cs as part of this importer is outdated. It contains some bugs, e.g. floats/doubles faulty being imported as integers on several systems where commas are used instead of dots. If people are facing same issue, update the simpleJSON.

From changelog simpleJSON:

https://github.com/Bunny83/SimpleJSON/blob/master/Changelog.txt

 * [2018-01-09 Update]
Changed all double.TryParse and double.ToString uses to use the invariant culture to avoid problems on systems with a culture that uses a comma as decimal point.

**Comment by kkukshtel** [comment]
@ntilborg is it as easy as just updating the simple JSON lib? Would gladly do it, or happy to accept a PR where you bump the version.

**Comment by ntilborg** [comment]
Yes I created PR #17

**Comment by kkukshtel** [comment]
Just left a comment - if you can include the changelog for SimpleJSON as part of the commit I'm happy to merge!

**Comment by kkukshtel** [comment]
Merged!
